# Copyright 1999-2021 Ineluctable Overlay Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
adler32-1.0.4
aho-corasick-0.7.10
ansi_term-0.11.0
ansi_term-0.12.1
atty-0.2.14
autocfg-1.0.0
bitflags-1.2.1
byteorder-1.3.4
cc-1.0.50
cfg-if-0.1.10
clap-2.33.0
clicolors-control-1.0.1
cloudabi-0.0.3
color_quant-1.0.1
console-0.7.7
crossbeam-deque-0.7.3
crossbeam-epoch-0.8.2
crossbeam-queue-0.2.1
crossbeam-utils-0.7.2
deflate-0.7.20
directories-1.0.2
either-1.5.3
encode_unicode-0.3.6
enquote-1.0.3
getopts-0.2.21
gif-0.10.3
heck-0.3.1
hermit-abi-0.1.10
hex-0.4.2
image-0.21.3
inflate-0.4.5
itoa-0.4.5
jpeg-decoder-0.1.18
lazy_static-1.4.0
libc-0.2.68
lock_api-0.3.3
lzw-0.10.0
maybe-uninit-2.0.0
memchr-2.3.3
memoffset-0.5.4
num-derive-0.2.5
num-integer-0.1.42
num-iter-0.1.40
num-rational-0.2.4
num-traits-0.2.11
num_cpus-1.12.0
paper-terminal-2.0.1
parking_lot-0.10.0
parking_lot_core-0.7.0
png-0.14.1
proc-macro2-0.4.30
proc-macro2-1.0.10
pulldown-cmark-0.4.1
quote-0.6.13
quote-1.0.3
rayon-1.3.0
rayon-core-1.7.0
redox_syscall-0.1.56
regex-1.3.6
regex-syntax-0.6.17
ryu-1.0.3
scoped_threadpool-0.1.9
scopeguard-1.1.0
serde-1.0.106
serde_derive-1.0.106
serde_json-1.0.50
smallvec-1.2.0
strsim-0.8.0
structopt-0.2.18
structopt-derive-0.2.18
syn-0.15.44
syn-1.0.17
syncat-stylesheet-2.2.0
terminal_size-0.1.11
termios-0.3.1
textwrap-0.11.0
thread_local-1.0.1
tiff-0.2.2
tree-sitter-0.6.3
unicase-2.6.0
unicode-segmentation-1.6.0
unicode-width-0.1.7
unicode-xid-0.1.0
unicode-xid-0.2.0
vec_map-0.8.1
version_check-0.9.1
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Writes a file to a paper in your terminal. Especially if that file is Markdown."
HOMEPAGE="https://github.com/foxfriends/paper-terminal"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"

LICENSE="Apache-2.0 BSD-2 BSL-1.1 MIT Unlicense ZLIB"
SLOT="0"
KEYWORDS="amd64 x86"
