#!/sbin/runscript
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	after vde
}


start() {
	ebegin "Starting slirpvde"
	start-stop-daemon --start --quiet \
		--exec /usr/bin/slirpvde \
			-- ${SLIRPVDE_OPTS} 
	eend $? "Failed to start slirpvde"
}

stop() {
	ebegin "Stopping slirpvde"
	start-stop-daemon --stop --quiet \
		--exec /usr/bin/slirpvde
	eend $? "Failed to stop slirpvde"
}
